source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
target 'SealTalk' do
  use_frameworks!
  pod 'Masonry', '1.1.0'
  pod 'AFNetworking', '4.0.1'
  pod 'FMDB','2.7.5'
  pod 'GCDWebServer/Core','3.5.2'
  pod 'GCDWebServer/WebDAV','3.5.2'
  pod 'GCDWebServer/WebUploader','3.5.2'
  pod 'ZXingObjC', '3.6.5'
  pod 'MBProgressHUD', '1.1.0'
  pod 'SSZipArchive', '2.2.2'
  pod 'SDWebImage', '5.0.6'
  pod 'Bugly', '2.5.91'
  pod 'UMCCommon', '7.3.5'
  pod 'FURenderKit', '8.3.0'
  
  pod 'RongCloudIM/IMLib', '5.2.4'
  pod 'RongCloudIM/IMKit', '5.2.4'
  pod 'RongCloudIM/RongSticker', '5.2.4'
  pod 'RongCloudIM/Sight', '5.2.4'
  pod 'RongCloudIM/ContactCard', '5.2.4'
  pod 'RongCloudIM/LocationKit', '5.2.4'
  pod 'RongCloudRTC/RongCallLib', '5.2.4'
#  pod 'RongCloudRTC/RongCallKit', '5.2.4'
end

